### ISSUE TITLE
[download fail]: Freezzing youtube.com

### ISSUE THREAD

**Issue by sorousheta** [iawia002/lux#1373]
**Website name**: www.youtube.com

**OS:**: Windows 10

**Video URL:**: https://www.youtube.com/watch?v=sJfoFnh9LgY

 0 B / 15.15 GiB [---------------------------------------------------------------------------------------] ? p/s 0.00% ?Downloading https://www.youtube.com/watch?v=sJfoFnh9LgY error:
https://rr3---sn-5hne6nsy.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&bui=AXc671JRrexIL-dub1EUsZLehGnbAW41sfNom6fouULufZ4OllaE5YX4st-nAHXPRSSLLEdkLpPP9MJs&c=WEB&clen=16156462306&dur=7501.360&ei=15eTZuGDMcHj6dsPhauZYA&expire=1720970295&fvip=4&gir=yes&id=o-AFplchYHtbbLNQpdboG7ba-mOBVcnSzEgOkrCiX5O2ro&initcwndbps=308750&ip=167.99.42.228&itag=313&keepalive=yes&lmt=1699312793614332&lsig=AHlkHjAwRQIhAIZdetnWXhV0mr1zdBtGvmu3ol9HuG8pB0YfgYZcGRlDAiAbAX9rj7YHd9Bmxy2BuPO6jWB-DA1a1MJ-Kw5UG2hPNA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=pu&mime=video%2Fwebm&mm=31%2C29&mn=sn-5hne6nsy%2Csn-5hnednsz&ms=au%2Crdu&mt=1720948384&mv=m&mvi=3&n=G5wQzblojgUJIHfzyME&ns=fssNW3IJanjjN9Xnzuh30QsQ&pl=20&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRQIhALe_NPOlZs_wSyBWtf6u54k1ATMEd-_XCh3eTU7MaVZPAiBM9kVeEmeN20AD6x8MjMY45oOZD9o85psyH5weDyGYbQ%3D%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=NO7bAQXLdtiFvbLKqPC20B_KDJuWw6LCXsyhVihxvCFlYt7TOLk36mtpDzL5&svpuc=1&txp=5432434&vprv=1&xpc=EgVo2aDSNQ%3D%3D request error: HTTP 403
github.com/iawia002/lux/request.Request
        /home/runner/work/lux/lux/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        /home/runner/work/lux/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        /home/runner/work/lux/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        /home/runner/work/lux/lux/downloader/downloader.go:675
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695
github.com/iawia002/lux/request.Request
        /home/runner/work/lux/lux/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        /home/runner/work/lux/lux/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        /home/runner/work/lux/lux/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        /home/runner/work/lux/lux/downloader/downloader.go:675
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695

**Stack overflow**

```
error message here
```

**Screenshots**

none

**Additional context**

none

**Comment by elaninhust** [comment]
that is a known bug that has been fixed. but they haven't released the latest version. u can just build a local one yourself

**Comment by Lao-Shen** [comment]
After go install github.com/iawia002/lux@latest, the same error still occurs
`$ HTTPS_PROXY="http://127.0.0.1:10809" lux "https://www.youtube.com/shorts/f_-AhpYJh_k"

 Site:      YouTube youtube.com
 Title:     Gotta reload to keep shooting [Compilation PART 64]
 Type:      video
 Stream:
     [299]  -------------------
     Quality:         1080p60 video/mp4; codecs="avc1.64002a"
     Size:            11.37 MiB (11921906 Bytes)
     # download with: lux -f 299 ...

0 B / 11.37 MiB [-----------------------------------------------------------------------------------------------------------------------] ? p/s 0.00% ?Downloading https://www.youtube.com/shorts/f_-AhpYJh_k error:
https://rr1---sn-a5mekndz.googlevideo.com/videoplayback?bui=AQmm2exYhJqkGEoP6LG9aPWFAD5Z_JyQH68sWiKmzq-XoRvHVlKKTG8XRrd2QVs62HomfkQzlKmjuykp&c=WEB&clen=269768&dur=16.602&ei=ex3QZuC7MMPisfIPvoC60AY&expire=1724936667&fvip=5&gir=yes&id=o-AF1YnLHz5kcZeGzcYrX3GCrY81RDMxMWaAT7jFZHhb0E&initcwndbps=1352500&ip=148.135.126.196&itag=140&keepalive=yes&lmt=1713002471207685&lsig=AGtxev0wRQIhAP_hAZD_H3TDhiK2dW168slmWlslh7ke13sOHUYXFbkPAiAzd4XbVaCfMlvykVnw_tAvvQYXo-v1ncxg0LyuZhyeWg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=om&mime=audio%2Fmp4&mm=31%2C29&mn=sn-a5mekndz%2Csn-a5msenes&ms=au%2Crdu&mt=1724914637&mv=m&mvi=1&n=YtjixpWn8sLHytRzuK&ns=84AOnr0_vAv5YMuIDSuoIUsQ&pl=17&requiressl=yes&rqh=1&sefc=1&sig=AJfQdSswRgIhALlVxS_6xIxMjT4gd6a3jTrAXYPoIlhE718MXikgwwirAiEArsAUWyjTiC9fX9vq1d1FZG2MmMRqwMJJFzOL2Io184w%3D&source=youtube&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&spc=Mv1m9p6f64JyspQfHEgHQDsrG9O4VQfUYzdToKG-iTcTp5xvOQ8fhJ57hkFY&svpuc=1&txp=5532434&vprv=1&xpc=EgVo2aDSNQ%3D%3D&xtags=drc%3D1 request error: HTTP 403
github.com/iawia002/lux/request.Request
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:116
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:1695
github.com/iawia002/lux/request.Request
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/request/request.go:118
github.com/iawia002/lux/downloader.(*Downloader).writeFile
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:110
github.com/iawia002/lux/downloader.(*Downloader).save
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:194
github.com/iawia002/lux/downloader.(*Downloader).Download.func1
        C:/Users/Administrator/go/pkg/mod/github.com/iawia002/lux@v0.24.1/downloader/downloader.go:675
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:1695`
